name: Facturas CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:

    runs-on: ubuntu-latest
    container: node:12.18.4

    services:
      mongo:
        image: mongo:4.2.2

    steps:
      - name: Descargar contenido del repositorio
        uses: actions/checkout@v2
      - name: Cachear node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Instalar las dependencias
        run: npm install
      - name: Ejecutar los tests
        run: npm test -- --coverage
        env:
          MONGO_URI: "mongodb://mongo/finanzas"
      - name: Subir coverage como un artefacto
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage

  publish-backend:

    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Descargar el código
        uses: actions/checkout@v2
      - name: Deploy en Heroku
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "practica-dblandit-lszikora"
          heroku_email: "lszikora@dblandit.com"

  publish-backend-docker:

    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v2
      - name: Construir y publicar la imagen Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USER }}/facturas-backend
          tag_with_ref: true